### ISSUE TITLE
Question about the AE experiment

### ISSUE THREAD

**Issue by yuanqidu** [vgsatorras/egnn#1]
Hi, I am a little confused by the AE experiment. The input data for the AE experiment is a fully-connected graph. I understand that the "attention" parameter is turned on while feeding a fully-connected graph and let the model infer edges, but it is only the case in the QM9 experiment. In the AE experiment, the attention parameter is set to False and the given graph is still fully-connected. Would you mind explaining a little bit about it? 

Thanks for your time!

**Comment by vgsatorras** [comment]
Hi Yuan,

Exactly, when the attention parameter is turned on, a soft representation of the edges is inferred. But we only used attention in the QM9 experiment. In the AE we didn't use it, then just a fully connected graph is assumed.

Best,
Victor

**Comment by yuanqidu** [comment]
Thanks for your quick response! 

I believe it is for the specific setting, meaning to tackle the symmetry problem, right? So, if I would like to work on a different graph, where the input edge connections are important, should I include the real graph connection rather than a fully-connected graph?

Yuanqi

**Comment by vgsatorras** [comment]
I would say yes, you should include them. Notice that in our graph auto-encoding experiment we also have edge connections that define the graph and are required. But we included them as edge attributes (check [line](https://github.com/vgsatorras/egnn/blob/1a2d515e069272484b4ff51930a3d5df3eeef92b/main_ae.py#L109), variable `edge_attr`). Even if we send messages between all nodes (fully connected message passing) the input to each edge operation receives a 0 or 1 value depending whether that edge exists or not in the input graph.

This is a valid solution as long as you do not have to scale to very large graphs since messages scale M^2 with respect to the number of nodes M. So if that is your case, you can just encode your edges as the `edge_attr` variables and directly use the model from our experiment. On the other hand, if you need to scale to very large graphs, you may want to include sparsity and then you may have to do moodify the `edges` variable.

I hope this helped,
Best,
Victor

**Comment by yuanqidu** [comment]
Thanks for your detailed explanations!

I see. Actually, I saw the edge connection was concatenated into the edge features. I was wondering whether this way is equivalent to feed a sparse graph. Oh, I see. So, the edge_mlp figures out the relationships of the features and calculations via BP (similar to the attention in the QM9 model). So, I believe two ways are somehow equivalent, right? I am just trying to understand the difference between the two ways.

Best,
Yuanqi

**Comment by vgsatorras** [comment]
It was a pleasure to meet you at the poster session. Closing the issue. Regarding the last question, edge connections were concatenated as an edge feature. Notice this is a more generic solution than just setting those edges to 0 since we still send messages among all nodes and it is up to the network to figure out those relationships as you said. Also notice that when scaling to larger graphs (it is not the case in our paper) it may be desirable to include sparsity since the number of edges scales O(N^2).

Best,
Victor
