### ISSUE TITLE
In place operation in `coord_model()` of `egnn_clean.py`

### ISSUE THREAD

**Issue by Olimoyo** [vgsatorras/egnn#3]
Thanks for sharing the code for this paper!

I ran into some autograd issues with the following in place operation:

https://github.com/vgsatorras/egnn/blob/dcd37610639d3e2d9836c3931756d706b3b2d47f/models/egnn_clean/egnn_clean.py#L81

Is this a bug or was it done intentionally for some other reason?

**Comment by vgsatorras** [comment]
Hi,

Thank you for letting us know. This in-place operation does not seem to create problems in the provided experiments. Did you run into these issues when using the model in a different project? Was it fixed by writing "coord = coord + agg" instead?

In any case, I have just modified that line to "coord = coord + agg" to avoid future in-place operation issues.

Best,
Victor

**Comment by Olimoyo** [comment]
It was with a different project and "coord = coord + agg" fixed it.
